language: python


# Align the matrix with the corresponding TOXENV settings
# to configure the correct variant for each tox invocation.
matrix:
  include:
    - python: "2.6"
      env: TOXENV=py26
    - python: "2.7"
      env: TOXENV=py27


install:
  - pip install -e .[test]
  - pip install coveralls
  - pip install tox
  - pip freeze

script:
  tox

after_success:
  # only get coverage on python-2.7
  - test $TOXENV = py27 && coveralls --rcfile coveragerc
